"""initial_schema"""
from alembic import op
import sqlalchemy as sa


revision = 'b17b317c1bb3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_kind'), 'content', ['kind'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('adult_gates',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('answer_hash', sa.String(length=64), nullable=False),
    sa.Column('grant_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('balances',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('wallet', sa.Integer(), nullable=False),
    sa.Column('savings', sa.Integer(), nullable=False),
    sa.CheckConstraint('wallet >= 0 AND savings >= 0'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('goals',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.CheckConstraint('target > 0'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('operations',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'operation_id')
    )
    op.create_table('periods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('income_claimed', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('spent_required', sa.Integer(), nullable=False),
    sa.Column('spent_wanted', sa.Integer(), nullable=False),
    sa.Column('saved', sa.Integer(), nullable=False),
    sa.Column('withdrawn', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'number')
    )
    op.create_index(op.f('ix_periods_profile_id'), 'periods', ['profile_id'], unique=False)
    op.create_table('pets',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('body', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('accessory', sa.String(length=20), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('satiety', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.CheckConstraint('mood BETWEEN 0 AND 100 AND satiety BETWEEN 0 AND 100 AND stage BETWEEN 1 AND 3'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('quest_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('quest_id', sa.String(length=80), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.String(length=40), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'quest_id')
    )
    op.create_index(op.f('ix_quest_attempts_profile_id'), 'quest_attempts', ['profile_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('wallet_delta', sa.Integer(), nullable=False),
    sa.Column('savings_delta', sa.Integer(), nullable=False),
    sa.Column('wallet_after', sa.Integer(), nullable=False),
    sa.Column('savings_after', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_profile_id'), 'transactions', ['profile_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_profile_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_quest_attempts_profile_id'), table_name='quest_attempts')
    op.drop_table('quest_attempts')
    op.drop_table('pets')
    op.drop_index(op.f('ix_periods_profile_id'), table_name='periods')
    op.drop_table('periods')
    op.drop_table('operations')
    op.drop_table('goals')
    op.drop_table('balances')
    op.drop_table('adult_gates')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_content_kind'), table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###
